name: escala_louvor
description: App para controle da escala do louvor.

# INSTRUÇÕES PARA BUILD 
# Para publicar a versão web no servidor local executar: 
# - flutter build web
# então copiar arquivos resultantes para a pasta definida no servidor IIS
#
# Para publicar no github pages executar:
# - flutter pub global run peanut --web-renderer canvaskit
# - git push -f origin --set-upstream gh-pages (-f é necessário para refazer a base)
#
# Para gerar a versão para Android tipo appbundle: 
# - flutter build appbundle --no-shrink
#
# Remover essa linha para publicar no repositório pub.dev
# - pub publish
publish_to: 'none'

# VERSÃO DO APP
version: 0.2.0+9

# VERSÃO DO SDK FLUTTER
environment:
  sdk: ">=2.16.1 <3.0.0"

# DEPENDÊNCIAS
# Após cada alteração neste arquivo executar: - flutter pub get
# Para atualizar para as últimas versões: - flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_modular: ^4.2.0
  flutter_local_notifications: ^9.4.0
  firebase_auth: ^3.3.13
  firebase_core: ^1.13.1
  # firebase_database: ^9.0.11
  firebase_messaging: ^11.2.11
  firebase_storage: ^10.2.11
  cloud_firestore: ^3.1.11
  easy_mask: ^2.0.1
  file_picker: ^4.5.1
  http: ^0.13.4
  intl: ^0.17.0
  pdf: ^3.7.2
  printing: ^5.7.5
  table_calendar: ^3.0.4
  shared_preferences: ^2.0.13
  connectivity_plus: ^2.3.0
  url_launcher: ^6.0.20
  url_strategy: ^0.2.0 # para remover o hash '#' das URLs (incluir 'setPathUrlStrategy();' em main) 

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4

flutter_app_name:
  name: 'Escala Louvor'
  
flutter_icons:
  image_path: 'assets/icons/ic_launcher.png'
  android: true
  ios: true

# ASSETS
flutter:
  uses-material-design: true
  assets:
    - dotenv.txt
    - assets/icons/ic_launcher.png
    # ÍCONES MÚSICA: https://www.flaticon.com/packs/music-icons-7?word=music%20instruments
    - assets/icons/music_baixo.png
    - assets/icons/music_bateria.png
    - assets/icons/music_coordenador.png
    - assets/icons/music_dirigente.png
    - assets/icons/music_guitarra.png
    - assets/icons/music_percussao.png
    - assets/icons/music_sonorizacao.png
    - assets/icons/music_sopro.png
    - assets/icons/music_teclado.png
    - assets/icons/music_transmissao.png
    - assets/icons/music_violao.png
    - assets/icons/music_voz.png
    # ILUSTRAÇÕES: https://icons8.com/illustrations/style--clip
    - assets/images/login.png
    - assets/images/chat.png
    - assets/images/church.png
    - assets/images/song.png
  fonts:
    - family: Offside
      fonts:
        - asset: assets/fonts/Offside-Regular.ttf
