name: escala_louvor
description: App para controle da escala do louvor.

# INSTRUÇÕES PARA BUILD 
# Para publicar a versão web no servidor local executar: 
# - flutter build web
# então copiar arquivos resultantes para a pasta definida no servidor IIS
#
# Para publicar no github pages executar:
# - flutter pub global run peanut --web-renderer canvaskit
# - git push -f origin --set-upstream gh-pages (-f é necessário para refazer a base)
#
# Para gerar a versão para Android tipo appbundle: 
# - flutter build appbundle --no-shrink
#
# Remover essa linha para publicar no repositório pub.dev
# - pub publish
publish_to: 'none'

# VERSÃO DO APP
version: 0.3.2+14

# VERSÃO DO SDK FLUTTER
environment:
  sdk: ">=2.17.0 <3.0.0"

# DEPENDÊNCIAS
# Após cada alteração neste arquivo executar: - flutter pub get
# Para atualizar para as últimas versões: - flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.1.17
  connectivity_plus: ^2.3.0
  easy_mask: ^2.0.1
  file_picker: ^4.6.0
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  firebase_storage: ^10.2.17
  flutter_dotenv: ^5.0.2
  flutter_modular: ^5.0.2
  flutter_local_notifications: ^9.5.3+1
  flutter_slidable: ^1.3.0
  font_awesome_flutter: ^10.1.0
  http: ^0.13.4
  intl: ^0.17.0
  package_info_plus: ^1.4.2
  pdf: ^3.8.1
  printing: ^5.9.1
  shared_preferences: ^2.0.15
  stylish_bottom_bar: ^0.1.3
  table_calendar: ^3.0.6
  upgrader: ^4.1.2
  url_launcher: ^6.1.2
  url_strategy: ^0.2.0 # para remover o hash '#' das URLs (incluir 'setPathUrlStrategy();' em main) 
  wakelock: ^0.6.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1

flutter_app_name:
  name: 'Escala do Louvor'
  
flutter_icons:
  image_path: 'assets/icons/ic_launcher.png'
  android: true
  ios: true

# ASSETS
flutter:
  uses-material-design: true
  assets:
    - dotenv.txt
    - assets/icons/ic_launcher.png
    - assets/icons/ic_disponivel.png
    - assets/icons/ic_escalado.png
    - assets/icons/ic_indeciso.png
    - assets/icons/ic_restrito.png
    # ÍCONES MÚSICA: https://www.flaticon.com/packs/music-icons-7?word=music%20instruments
    - assets/icons/music_baixo.png
    - assets/icons/music_bateria.png
    - assets/icons/music_coordenador.png
    - assets/icons/music_dirigente.png
    - assets/icons/music_guitarra.png
    - assets/icons/music_percussao.png
    - assets/icons/music_sonorizacao.png
    - assets/icons/music_sopro.png
    - assets/icons/music_teclado.png
    - assets/icons/music_transmissao.png
    - assets/icons/music_violao.png
    - assets/icons/music_voz.png
    # ILUSTRAÇÕES: https://icons8.com/illustrations/style--clip
    - assets/images/login.png
    - assets/images/chat.png
    - assets/images/church.png
    - assets/images/song.png
  fonts:
    - family: Offside
      fonts:
        - asset: assets/fonts/Offside-Regular.ttf
    - family: OpenSansSemiCondensed
      fonts:
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans_SemiCondensed-Light.ttf
          weight: 300
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
