name: escala_louvor
description: Um app para controle da escala da equipe de louvor

# INSTRUÇÕES PARA BUILDS

# Para publicar a versão web no servidor local executar: 
# - flutter build web --web-renderer canvaskit
# OU
# - flutter build web --base-href /escala_louvor/
# então copiar arquivos resultantes para a pasta definida no servidor IIS
#
# Para publicar no Firebase Hosting
# - flutter build web --web-renderer canvaskit
# - firebase deploy
#
# Para publicar no github pages executar:
# - flutter pub global run peanut --web-renderer canvaskit --extra-args "--base-href=/escala_louvor/"
# - git push -f origin --set-upstream gh-pages (-f é necessário para refazer a base)
#
# Para gerar a versão para Android tipo appbundle: 
# - flutter build appbundle --no-shrink

# Remover essa linha para publicar no repositório pub.dev
# - pub publish
publish_to: 'none'

# VERSÃO DO APP
version: 0.3.10+17

# VERSÃO DO SDK FLUTTER
environment:
  sdk: ">=2.17.0 <3.0.0"

# DEPENDÊNCIAS
# Após cada alteração neste arquivo executar: - flutter pub get
# Para atualizar para as últimas versões: - flutter pub upgrade --major-versions
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  ## Bibliotecas FIREBASE  ##
  firebase_core: ^1.18.0 # Core
  firebase_auth: ^3.3.20 # Autenticação de usuários
  firebase_storage: ^10.2.18 # Storage de dados
  cloud_firestore: ^3.1.18 # Storage de arquivos
  firebase_messaging: ^11.4.2 # Cloud Messaging
  ## Ferramentas básicas ##
  flutter_modular: ^5.0.2 # Gerenciador de estados e navegação
  flutter_local_notifications: ^9.6.1 # Sistema de notificações locais
  http: ^0.13.4 # Base para web
  intl: ^0.17.0 # Base para idiomas
  package_info_plus: ^1.4.2 # Recolhe dados básicos do app
  shared_preferences: ^2.0.15 # Cache para dados do usuário
  url_launcher: ^6.1.2 # Base para abrir links
  ## Ferramentas para imagens e arquivos ##
  cached_network_image: ^3.2.1 # Economizar banda com imagens em cache
  image_cropper: ^2.0.3 # Para manipulação de imagens
  image_picker: ^0.8.5+3 # Para seleção de imagens
  file_picker: ^4.6.0 # Para seleção de arquivos
  #pdf: ^3.8.1 # Gerar PDFs
  printing: ^5.9.1 # Abrir PDFs
  ## Ferramentas acessórias ##
  easy_mask: ^2.0.1 # Máscara para inputs de texto
  flutter_dotenv: ^5.0.2 # Esconder arquivo de chaves
  flutter_quill: ^5.0.3 # Para edição de RichText
  upgrader: ^4.4.0 # Verificador de novas versões com notificador
  wakelock: ^0.6.1+2 # Mantêm a tela sempre ligada
  ## Widgets especiais ##
  carousel_slider: ^4.1.1 # Widget tipo carrosel de imagens  
  flutter_slidable: ^1.3.0 # Widget tipo list tile com função slide para mostrar ações
  stylish_bottom_bar: ^0.1.3 # Widget tipo bottom bar com float button
  table_calendar: ^3.0.6 # Widget tipo calendário
  
dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1

flutter_app_name:
  name: 'Escala do Louvor'
  
flutter_icons:
  image_path: 'assets/icons/ic_launcher.png'
  android: true
  ios: true

# ASSETS
flutter:
  uses-material-design: true
  assets:
    - dotenv.txt
    - assets/icons/ic_launcher.png
    - assets/icons/ic_disponivel.png
    - assets/icons/ic_escalado.png
    - assets/icons/ic_indeciso.png
    - assets/icons/ic_restrito.png
    # ÍCONES MÚSICA: https://www.flaticon.com/packs/music-icons-7?word=music%20instruments
    - assets/icons/music_baixo.png
    - assets/icons/music_bateria.png
    - assets/icons/music_coordenador.png
    - assets/icons/music_dirigente.png
    - assets/icons/music_guitarra.png
    - assets/icons/music_percussao.png
    - assets/icons/music_piano.png
    - assets/icons/music_sonorizacao.png
    - assets/icons/music_sopro.png
    - assets/icons/music_teclado.png
    - assets/icons/music_transmissao.png
    - assets/icons/music_violao.png
    - assets/icons/music_voz.png
    # ILUSTRAÇÕES: https://icons8.com/illustrations/style--clip
    - assets/images/login.png
    - assets/images/chat.png
    - assets/images/church.png
    - assets/images/fail.png
    - assets/images/song.png
  fonts:
    - family: Offside
      fonts:
        - asset: assets/fonts/Offside-Regular.ttf
    - family: OpenSansSemiCondensed
      fonts:
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans_SemiCondensed-Light.ttf
          weight: 300
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
          style: italic
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Ubuntu-Light.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-LightItalic.ttf
          weight: 300
          style: italic
