// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp_lsWvNrPhSCKoW3eXS1uDoxXGdBBWns',
    appId: '1:420088880029:web:7f20d85ded9fd777482d74',
    messagingSenderId: '420088880029',
    projectId: 'escala-louvor-ipbfoz',
    authDomain: 'escala-louvor-ipbfoz.firebaseapp.com',
    databaseURL: 'https://escala-louvor-ipbfoz-default-rtdb.firebaseio.com',
    storageBucket: 'escala-louvor-ipbfoz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpmgjkDtQv1Ca_m8arqTvsKsaqrNnufNo',
    appId: '1:420088880029:android:6e8470c1c5095153482d74',
    messagingSenderId: '420088880029',
    projectId: 'escala-louvor-ipbfoz',
    databaseURL: 'https://escala-louvor-ipbfoz-default-rtdb.firebaseio.com',
    storageBucket: 'escala-louvor-ipbfoz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6_P1jvLUnA0r6k9n9-meO6viqdSxs6KI',
    appId: '1:420088880029:ios:83e0732a1b33bad5482d74',
    messagingSenderId: '420088880029',
    projectId: 'escala-louvor-ipbfoz',
    databaseURL: 'https://escala-louvor-ipbfoz-default-rtdb.firebaseio.com',
    storageBucket: 'escala-louvor-ipbfoz.appspot.com',
    androidClientId: '420088880029-k909hketimsl2gsfhptk4oo6q6t0eba3.apps.googleusercontent.com',
    iosClientId: '420088880029-p661620l119hqv9rcr6ijc8bpia28uld.apps.googleusercontent.com',
    iosBundleId: 'br.org.ipbfoz.escalaLouvor',
  );
}
